# Site settings
author: DAISY M KIYEMBA
title: REMOTE CODER TRAVELER
header-img: img/home-bg.png
email: deedaisy29@gmail.com
copyright_name: DAISY M KIYEMBA
description: > # this means to ignore newlines until "baseurl:"
  CODE TRAVEL WORLD
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  daisykiyemba

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
